CREATE OR REPLACE TRIGGER  "AT_TIME" 
BEFORE INSERT ON spec
FOR EACH ROW
 WHEN (new.time is null) begin
SELECT TO_CHAR (SYSDATE, 'MM-DD-YYYY HH24:MI:SS') "NOW"
INTO :NEW.time
FROM DUAL;
END;
/
ALTER TRIGGER  "AT_TIME" ENABLE;

CREATE OR REPLACE TRIGGER  "NEWID" 
BEFORE INSERT ON spec
FOR EACH ROW
 WHEN (NEW.SPEC_ID IS NULL) BEGIN
SELECT spec_seq.NEXTVAL
INTO :NEW.SPEC_ID
FROM DUAL;
END;
/
ALTER TRIGGER  "NEWID" ENABLE;
