/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectdb_spec;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static projectdb_spec.Login.my;

/**
 *
 * @author AUSU
 */
public class Catalog extends javax.swing.JFrame {

    /**
     * Creates new form catalog
     */
    public String logid = "";
    public String date = "";

    public Catalog(String uid) {
        initComponents();
        logid = uid;
        try {
            DefaultTableModel model = (DefaultTableModel) catalogtable.getModel();
            model.setRowCount(0);
            ResultSet rs = my.getAllspec(uid);
            while (rs.next()) {
                String time = rs.getString("time");
                String price = rs.getString("price");
                String des = rs.getString("cpu") + rs.getString("vga") + rs.getString("mb");
                model.addRow(new String[]{time, des, price});
            }
        } catch (Exception exc) {
            System.out.println("Err: " + exc);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Detets = new javax.swing.JButton();
        newspec = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        catalogtable = new javax.swing.JTable();
        edit = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(707, 456));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Detets.setIcon(new javax.swing.ImageIcon("C:\\Users\\AUSU\\Desktop\\projectDB_spec\\image\\imageApp\\Delete.jpg")); // NOI18N
        Detets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetetsActionPerformed(evt);
            }
        });
        jPanel1.add(Detets, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 165, 75, 25));

        newspec.setIcon(new javax.swing.ImageIcon("C:\\Users\\AUSU\\Desktop\\projectDB_spec\\image\\imageApp\\Build.jpg")); // NOI18N
        newspec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newspecActionPerformed(evt);
            }
        });
        jPanel1.add(newspec, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 79, 75, 25));

        jPanel4.setBackground(new java.awt.Color(153, 255, 255));

        catalogtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "     Time", "Depasment", "     Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        catalogtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catalogtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(catalogtable);
        if (catalogtable.getColumnModel().getColumnCount() > 0) {
            catalogtable.getColumnModel().getColumn(0).setResizable(false);
            catalogtable.getColumnModel().getColumn(1).setResizable(false);
            catalogtable.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1074, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 79, -1, -1));

        edit.setIcon(new javax.swing.ImageIcon("C:\\Users\\AUSU\\Desktop\\projectDB_spec\\image\\imageApp\\Edit.jpg")); // NOI18N
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel1.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 122, 75, 25));

        logout.setIcon(new javax.swing.ImageIcon("C:\\Users\\AUSU\\Desktop\\projectDB_spec\\image\\imageApp\\Logout.jpg")); // NOI18N
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 762, 75, 25));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("MY SPEC");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 18, 198, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\AUSU\\Desktop\\projectDB_spec\\image\\imageApp\\BACK4.jpg")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1212, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1218, 847));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DetetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetetsActionPerformed

        int i;
        i = JOptionPane.showConfirmDialog(null, "Are you sure to delete spec ?");
        if (i == 0) {
            try {
                    my.deletespec(logid,date);
                    DefaultTableModel model = (DefaultTableModel) catalogtable.getModel();
                    model.setRowCount(0);
                    ResultSet rs = my.getAllspec(logid);
                    while (rs.next()) {
                        String time = rs.getString("time");
                        String price = rs.getString("price");
                        String des = rs.getString("cpu") + rs.getString("vga") + rs.getString("mb");
                        model.addRow(new String[]{time, des, price});
                    }

                

            } catch (SQLException ex) {
                Logger.getLogger(Catalog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_DetetsActionPerformed

    private void newspecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newspecActionPerformed
        setVisible(false);
        new Newspec(logid).setVisible(true);
    }//GEN-LAST:event_newspecActionPerformed


    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
               String specid="";
           if(!date.equals("")){    
            try {
             ResultSet rs =   my.getID(logid,date);
            while (rs.next()){
             specid = rs.getString("SPEC_ID");
            System.out.println(specid);
        }     
            
             setVisible(false);
           new Newspec(logid,specid).setVisible(true);
            }catch (SQLException ex) {
            Logger.getLogger(Catalog.class.getName()).log(Level.SEVERE, null, ex);
        }}
                
    }//GEN-LAST:event_editActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void catalogtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catalogtableMouseClicked
        DefaultTableModel model = (DefaultTableModel) catalogtable.getModel();
        int indextable = catalogtable.getSelectedRow();
        date = model.getValueAt(indextable, 0).toString();
        System.out.println(date);
    }//GEN-LAST:event_catalogtableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Detets;
    private javax.swing.JTable catalogtable;
    private javax.swing.JButton edit;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    private javax.swing.JButton newspec;
    // End of variables declaration//GEN-END:variables

   

   
}
